Fix integer max restaurantes issue and improve pipeline

diff --git a/.github/workflows/cria_lista_duo_metro_google_e_cria_release.yml b/.github/workflows/cria_lista_duo_metro_google_e_cria_release.yml
--- a/.github/workflows/cria_lista_duo_metro_google_e_cria_release.yml
+++ b/.github/workflows/cria_lista_duo_metro_google_e_cria_release.yml
@@ -31,7 +31,7 @@ jobs:
         pip install -r requirements.txt
         
     - name: Run Python script
-      run: python duo_google.py
+      run: python duo_google.py || { echo "Script failed"; exit 1; }
       
     - name: Upload artifact
       uses: actions/upload-artifact@v4
